const MOCHA_CONFIG = {
  G_SELENIUM_TESTING: false,
  G_TYPE_CZECH_ON: true,
  G_TYPE_CZECH_OPTIONS: ['LOG-ERRORS'],
  //G_TYPE_CZECH_OPTIONS: ['NO-ERROR-MESSAGES'],
  //G_TYPE_CZECH_OPTIONS: ['CONSOLE-COUNT', 'LOG-ERRORS']
}


module.exports = { MOCHA_CONFIG}

