name: Main-x
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.16.0"
      - name: Install ci
        run: npm install
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test
